# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84757ab1bdef8deca5734956b2057f82897e64067f789df41eb4d76b6a403751c05a820777a27391f7d8407843fd62ecf21c7eda2666a7d9a8875ba8b1321e75

test:
  secret_key_base: b61495392159026d75665d86ca48c5b509c747eda84b9388ebc2b06b3d4c6614fec08b124d490b7a5cac92dc18eb0b8a534f7216c207e174589d5262ec2227ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
